### PR TITLE
Feature/kx 85 edit resources after creation UI

### PR DESCRIPTION
**Pull request by GiuseppeArbore**

### CODE REVIEW

**Review by AlbertoPedalino — CHANGES_REQUESTED** [review]
image
dont like the layout of the page, i ll provide a sketch

image

**Comment by AlbertoPedalino** [comment]
i'm not able to submit. is normal?

**Comment by AlbertoPedalino** [comment]
change homepage redirect with dashboard redirect and so the icon

**Comment by GiuseppeArbore** [comment]
> change homepage redirect with dashboard redirect and so the icon

This branch is about UI (only UI, no frontend logic) to edit resources after creation

**Comment by GiuseppeArbore** [comment]
> image dont like the layout of the page, i ll provide a sketch
> 
> image

It was the previous version but it wasn't approved, so we moved to this one... IDK

**Review by AlbertoPedalino — APPROVED** [review]

**Pull request merged**
